### ISSUE TITLE
Set up reverse proxy for marketplace

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#727] opened 2021-05-10 22:03 UTC

**Comment by parulmishra** [comment] 2021-05-12 20:54
@scchapma @mark-a-wilson @nmathava 

**Status update till date on this ticket:** Created the caddyfile using the same approach that existing digital.gov wordpress site team is using through nginx.
**Work left on this ticket:** Testing the caddyfile from this PR https://github.com/bcgov/digital.gov.bc.ca/pull/708/files with the prod url of the marketplace

**Comment by mark-a-wilson** [comment] 2021-05-17 17:54
See documentation in comment thread on #729

**Comment by thegentlemanphysicist** [comment] 2021-05-19 18:51
Set up caddy to implement a reverse proxy from digital.gov.bc.ca -> marketplace

Direct traffic from:
url/marketplace/* to be handled by the marketplace app

Direct non /marketplace/ traffic to our digital.gov site.

This is done by modifying the react deployment config file where the caddy file is defined.

**Comment by thegentlemanphysicist** [comment] 2021-05-19 18:55
Backup plan: if Caddy doesn't work.  Try replacing with nginx.

**Comment by thegentlemanphysicist** [comment] 2021-05-19 22:46
putting this in blocked/on hold until openshift is working again

**Comment by SteveChapmanBCDX** [comment] 2021-05-25 19:18
Closing as duplicate of epic #746

**Closed by SteveChapmanBCDX** 2021-05-25 19:18 UTC
Labels: development
